-- ============================================================
-- SIMBAKES - Tabel akun_peserta (LENGKAP)
-- Jalankan SELURUH isi file ini di Supabase SQL Editor
-- URL: https://supabase.com/dashboard/project/boeknpvlfamjmddsdopd/sql
-- ============================================================

-- ============================================================
-- 1. DROP TABEL LAMA (jika ada, untuk clean install)
-- ============================================================
DROP TABLE IF EXISTS public.akun_peserta CASCADE;

-- ============================================================
-- 2. BUAT TABEL akun_peserta
-- ============================================================
CREATE TABLE public.akun_peserta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    nik VARCHAR(16) NOT NULL,
    email TEXT NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    jurusan_tujuan TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Constraint: NIK harus 16 digit angka
    CONSTRAINT akun_peserta_nik_valid CHECK (nik ~ '^[0-9]{16}$'),
    
    -- Unique constraints
    CONSTRAINT akun_peserta_nik_unique UNIQUE (nik),
    CONSTRAINT akun_peserta_email UNIQUE (email),
    CONSTRAINT akun_peserta_username UNIQUE (username)
);

-- ============================================================
-- 3. BUAT INDEX untuk performance
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_akun_peserta_nik ON public.akun_peserta(nik);
CREATE INDEX IF NOT EXISTS idx_akun_peserta_username ON public.akun_peserta(username);
CREATE INDEX IF NOT EXISTS idx_akun_peserta_email ON public.akun_peserta(email);
CREATE INDEX IF NOT EXISTS idx_akun_peserta_jurusan ON public.akun_peserta(jurusan_tujuan);

-- ============================================================
-- 4. ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================================
ALTER TABLE public.akun_peserta ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 5. BUAT RLS POLICIES
-- ============================================================

-- Policy: ANON bisa INSERT (untuk registrasi)
CREATE POLICY "allow_anon_insert" ON public.akun_peserta
    FOR INSERT TO anon
    WITH CHECK (true);

-- Policy: ANON bisa SELECT (untuk login verifikasi)
CREATE POLICY "allow_anon_select" ON public.akun_peserta
    FOR SELECT TO anon
    USING (true);

-- Policy: ANON bisa UPDATE (untuk update profil)
CREATE POLICY "allow_anon_update" ON public.akun_peserta
    FOR UPDATE TO anon
    USING (true)
    WITH CHECK (true);

-- Policy: Authenticated users bisa INSERT
CREATE POLICY "allow_auth_insert" ON public.akun_peserta
    FOR INSERT TO authenticated
    WITH CHECK (true);

-- Policy: Authenticated users bisa SELECT
CREATE POLICY "allow_auth_select" ON public.akun_peserta
    FOR SELECT TO authenticated
    USING (true);

-- Policy: Authenticated users bisa UPDATE
CREATE POLICY "allow_auth_update" ON public.akun_peserta
    FOR UPDATE TO authenticated
    USING (true)
    WITH CHECK (true);

-- ============================================================
-- 6. TRIGGER: Update updated_at otomatis
-- ============================================================

-- Function untuk update timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger pada tabel akun_peserta
DROP TRIGGER IF EXISTS trigger_akun_peserta_updated_at ON public.akun_peserta;

CREATE TRIGGER trigger_akun_peserta_updated_at
    BEFORE UPDATE ON public.akun_peserta
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================
-- 7. VERIFIKASI STRUKTUR TABEL
-- ============================================================
SELECT '✅ Tabel akun_peserta berhasil dibuat!' as status;

SELECT 
    column_name as kolom,
    data_type as tipe_data,
    is_nullable as boleh_kosong,
    column_default as default_value
FROM information_schema.columns 
WHERE table_name = 'akun_peserta' 
AND table_schema = 'public'
ORDER BY ordinal_position;

-- ============================================================
-- 8. CEK RLS & POLICIES
-- ============================================================
SELECT 
    policyname as nama_policy,
    cmd as operasi,
    roles as role_yang_diizinkan
FROM pg_policies 
WHERE tablename = 'akun_peserta';

-- ============================================================
-- CATATAN PENTING KEAMANAN:
-- ============================================================
/*
⚠️ PERINGATAN KEAMANAN:
------------------------
1. Password disimpan sebagai PLAINTEXT (tidak di-hash)
   - Ini aman untuk prototype/development
   - Untuk PRODUCTION, gunakan:
     * Supabase Auth (supabase.auth.signInWithPassword())
     * Atau hashing via Edge Function/Backend
   
2. RLS Policy menggunakan WITH CHECK (true) dan USING (true)
   - Ini membuka akses penuh ke tabel untuk ANON role
   - Untuk PRODUCTION, batasi policy:
     * INSERT: Hanya untuk registrasi baru
     * SELECT: Hanya user yang login (berdasarkan ID)
     * UPDATE: Hanya data milik sendiri

3. NIK disimpan sebagai VARCHAR(16) bukan BIGINT
   - Mencegah masalah leading zeros
   - NIK dengan awalan 0 tetap tersimpan benar

4. Rekomendasi untuk Production:
   - Gunakan bcrypt/argon2 untuk password hashing
   - Implementasikan rate limiting pada login
   - Tambahkan email verification
   - Gunakan HTTPS wajib
*/

-- ============================================================
-- SELESAI - Tabel siap digunakan!
-- ============================================================
